apiVersion: v1
kind: Pod
metadata:
  name: webserver-v3
  labels:
    app: nginxweb
    type: production
    ver: v3
spec:
  containers:
  - name: web
    image: kirank05/nginx:alpine
    ports:
    - containerPort: 80
