apiVersion: v1
kind: Pod
metadata:
  name: browser
spec:
  containers:
  - name: curl
    image: kirank05/curl
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo Pod running ; sleep 7200']
